/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cvg.sfmPipeline.main;

public class Frame {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Frame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Frame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sfmmatcherJNI.delete_Frame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Frame() {
    this(sfmmatcherJNI.new_Frame__SWIG_0(), true);
  }

  public Frame(SWIGTYPE_p_cv__Mat arg0) {
    this(sfmmatcherJNI.new_Frame__SWIG_1(SWIGTYPE_p_cv__Mat.getCPtr(arg0)), true);
  }

  public void extractFeatures() {
    sfmmatcherJNI.Frame_extractFeatures(swigCPtr, this);
  }

  public void addFrame(SWIGTYPE_p_cv__Mat arg0) {
    sfmmatcherJNI.Frame_addFrame(swigCPtr, this, SWIGTYPE_p_cv__Mat.getCPtr(arg0));
  }

  public boolean buildFrameProtoMessage(boolean doJPEG) {
    return sfmmatcherJNI.Frame_buildFrameProtoMessage(swigCPtr, this, doJPEG);
  }

  public byte[] getFrame() {
  return sfmmatcherJNI.Frame_getFrame(swigCPtr, this);
}

  public void setDescriptors(SWIGTYPE_p_cv__Mat value) {
    sfmmatcherJNI.Frame_Descriptors_set(swigCPtr, this, SWIGTYPE_p_cv__Mat.getCPtr(value));
  }

  public SWIGTYPE_p_cv__Mat getDescriptors() {
    return new SWIGTYPE_p_cv__Mat(sfmmatcherJNI.Frame_Descriptors_get(swigCPtr, this), true);
  }

}
