// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matches.proto

package cvg.sfmPipeline.main;

public final class MatchesOutMessage {
  private MatchesOutMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DMatchesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 queryIdx = 1;
    boolean hasQueryIdx();
    int getQueryIdx();
    
    // optional uint32 trainIdx = 2;
    boolean hasTrainIdx();
    int getTrainIdx();
    
    // optional uint32 imgIdx = 3;
    boolean hasImgIdx();
    int getImgIdx();
    
    // optional float distance = 4;
    boolean hasDistance();
    float getDistance();
  }
  public static final class DMatches extends
      com.google.protobuf.GeneratedMessage
      implements DMatchesOrBuilder {
    // Use DMatches.newBuilder() to construct.
    private DMatches(Builder builder) {
      super(builder);
    }
    private DMatches(boolean noInit) {}
    
    private static final DMatches defaultInstance;
    public static DMatches getDefaultInstance() {
      return defaultInstance;
    }
    
    public DMatches getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_DMatches_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_DMatches_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 queryIdx = 1;
    public static final int QUERYIDX_FIELD_NUMBER = 1;
    private int queryIdx_;
    public boolean hasQueryIdx() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getQueryIdx() {
      return queryIdx_;
    }
    
    // optional uint32 trainIdx = 2;
    public static final int TRAINIDX_FIELD_NUMBER = 2;
    private int trainIdx_;
    public boolean hasTrainIdx() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTrainIdx() {
      return trainIdx_;
    }
    
    // optional uint32 imgIdx = 3;
    public static final int IMGIDX_FIELD_NUMBER = 3;
    private int imgIdx_;
    public boolean hasImgIdx() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getImgIdx() {
      return imgIdx_;
    }
    
    // optional float distance = 4;
    public static final int DISTANCE_FIELD_NUMBER = 4;
    private float distance_;
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getDistance() {
      return distance_;
    }
    
    private void initFields() {
      queryIdx_ = 0;
      trainIdx_ = 0;
      imgIdx_ = 0;
      distance_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, queryIdx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, trainIdx_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, imgIdx_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, distance_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, queryIdx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, trainIdx_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, imgIdx_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, distance_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.DMatches parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cvg.sfmPipeline.main.MatchesOutMessage.DMatches prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_DMatches_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_DMatches_fieldAccessorTable;
      }
      
      // Construct using cvg.sfmPipeline.main.MatchesOutMessage.DMatches.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        queryIdx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        trainIdx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        imgIdx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        distance_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cvg.sfmPipeline.main.MatchesOutMessage.DMatches.getDescriptor();
      }
      
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatches getDefaultInstanceForType() {
        return cvg.sfmPipeline.main.MatchesOutMessage.DMatches.getDefaultInstance();
      }
      
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatches build() {
        cvg.sfmPipeline.main.MatchesOutMessage.DMatches result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cvg.sfmPipeline.main.MatchesOutMessage.DMatches buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cvg.sfmPipeline.main.MatchesOutMessage.DMatches result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatches buildPartial() {
        cvg.sfmPipeline.main.MatchesOutMessage.DMatches result = new cvg.sfmPipeline.main.MatchesOutMessage.DMatches(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.queryIdx_ = queryIdx_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.trainIdx_ = trainIdx_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.imgIdx_ = imgIdx_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.distance_ = distance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cvg.sfmPipeline.main.MatchesOutMessage.DMatches) {
          return mergeFrom((cvg.sfmPipeline.main.MatchesOutMessage.DMatches)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cvg.sfmPipeline.main.MatchesOutMessage.DMatches other) {
        if (other == cvg.sfmPipeline.main.MatchesOutMessage.DMatches.getDefaultInstance()) return this;
        if (other.hasQueryIdx()) {
          setQueryIdx(other.getQueryIdx());
        }
        if (other.hasTrainIdx()) {
          setTrainIdx(other.getTrainIdx());
        }
        if (other.hasImgIdx()) {
          setImgIdx(other.getImgIdx());
        }
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              queryIdx_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              trainIdx_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              imgIdx_ = input.readUInt32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              distance_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 queryIdx = 1;
      private int queryIdx_ ;
      public boolean hasQueryIdx() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getQueryIdx() {
        return queryIdx_;
      }
      public Builder setQueryIdx(int value) {
        bitField0_ |= 0x00000001;
        queryIdx_ = value;
        onChanged();
        return this;
      }
      public Builder clearQueryIdx() {
        bitField0_ = (bitField0_ & ~0x00000001);
        queryIdx_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 trainIdx = 2;
      private int trainIdx_ ;
      public boolean hasTrainIdx() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTrainIdx() {
        return trainIdx_;
      }
      public Builder setTrainIdx(int value) {
        bitField0_ |= 0x00000002;
        trainIdx_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrainIdx() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trainIdx_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 imgIdx = 3;
      private int imgIdx_ ;
      public boolean hasImgIdx() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getImgIdx() {
        return imgIdx_;
      }
      public Builder setImgIdx(int value) {
        bitField0_ |= 0x00000004;
        imgIdx_ = value;
        onChanged();
        return this;
      }
      public Builder clearImgIdx() {
        bitField0_ = (bitField0_ & ~0x00000004);
        imgIdx_ = 0;
        onChanged();
        return this;
      }
      
      // optional float distance = 4;
      private float distance_ ;
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getDistance() {
        return distance_;
      }
      public Builder setDistance(float value) {
        bitField0_ |= 0x00000008;
        distance_ = value;
        onChanged();
        return this;
      }
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000008);
        distance_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sfm.DMatches)
    }
    
    static {
      defaultInstance = new DMatches(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sfm.DMatches)
  }
  
  public interface MatchesProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional fixed64 imageLseq = 1;
    boolean hasImageLseq();
    long getImageLseq();
    
    // optional fixed64 imageRseq = 2;
    boolean hasImageRseq();
    long getImageRseq();
    
    // repeated .sfm.DMatches matches = 3;
    java.util.List<cvg.sfmPipeline.main.MatchesOutMessage.DMatches> 
        getMatchesList();
    cvg.sfmPipeline.main.MatchesOutMessage.DMatches getMatches(int index);
    int getMatchesCount();
    java.util.List<? extends cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder> 
        getMatchesOrBuilderList();
    cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder getMatchesOrBuilder(
        int index);
  }
  public static final class MatchesProto extends
      com.google.protobuf.GeneratedMessage
      implements MatchesProtoOrBuilder {
    // Use MatchesProto.newBuilder() to construct.
    private MatchesProto(Builder builder) {
      super(builder);
    }
    private MatchesProto(boolean noInit) {}
    
    private static final MatchesProto defaultInstance;
    public static MatchesProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public MatchesProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_MatchesProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_MatchesProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional fixed64 imageLseq = 1;
    public static final int IMAGELSEQ_FIELD_NUMBER = 1;
    private long imageLseq_;
    public boolean hasImageLseq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getImageLseq() {
      return imageLseq_;
    }
    
    // optional fixed64 imageRseq = 2;
    public static final int IMAGERSEQ_FIELD_NUMBER = 2;
    private long imageRseq_;
    public boolean hasImageRseq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getImageRseq() {
      return imageRseq_;
    }
    
    // repeated .sfm.DMatches matches = 3;
    public static final int MATCHES_FIELD_NUMBER = 3;
    private java.util.List<cvg.sfmPipeline.main.MatchesOutMessage.DMatches> matches_;
    public java.util.List<cvg.sfmPipeline.main.MatchesOutMessage.DMatches> getMatchesList() {
      return matches_;
    }
    public java.util.List<? extends cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder> 
        getMatchesOrBuilderList() {
      return matches_;
    }
    public int getMatchesCount() {
      return matches_.size();
    }
    public cvg.sfmPipeline.main.MatchesOutMessage.DMatches getMatches(int index) {
      return matches_.get(index);
    }
    public cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder getMatchesOrBuilder(
        int index) {
      return matches_.get(index);
    }
    
    private void initFields() {
      imageLseq_ = 0L;
      imageRseq_ = 0L;
      matches_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, imageLseq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, imageRseq_);
      }
      for (int i = 0; i < matches_.size(); i++) {
        output.writeMessage(3, matches_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, imageLseq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, imageRseq_);
      }
      for (int i = 0; i < matches_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, matches_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cvg.sfmPipeline.main.MatchesOutMessage.MatchesProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_MatchesProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cvg.sfmPipeline.main.MatchesOutMessage.internal_static_sfm_MatchesProto_fieldAccessorTable;
      }
      
      // Construct using cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMatchesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        imageLseq_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        imageRseq_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto.getDescriptor();
      }
      
      public cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto getDefaultInstanceForType() {
        return cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto.getDefaultInstance();
      }
      
      public cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto build() {
        cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto buildPartial() {
        cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto result = new cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.imageLseq_ = imageLseq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.imageRseq_ = imageRseq_;
        if (matchesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            matches_ = java.util.Collections.unmodifiableList(matches_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.matches_ = matches_;
        } else {
          result.matches_ = matchesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto) {
          return mergeFrom((cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto other) {
        if (other == cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto.getDefaultInstance()) return this;
        if (other.hasImageLseq()) {
          setImageLseq(other.getImageLseq());
        }
        if (other.hasImageRseq()) {
          setImageRseq(other.getImageRseq());
        }
        if (matchesBuilder_ == null) {
          if (!other.matches_.isEmpty()) {
            if (matches_.isEmpty()) {
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMatchesIsMutable();
              matches_.addAll(other.matches_);
            }
            onChanged();
          }
        } else {
          if (!other.matches_.isEmpty()) {
            if (matchesBuilder_.isEmpty()) {
              matchesBuilder_.dispose();
              matchesBuilder_ = null;
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000004);
              matchesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMatchesFieldBuilder() : null;
            } else {
              matchesBuilder_.addAllMessages(other.matches_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              imageLseq_ = input.readFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              imageRseq_ = input.readFixed64();
              break;
            }
            case 26: {
              cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder subBuilder = cvg.sfmPipeline.main.MatchesOutMessage.DMatches.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMatches(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional fixed64 imageLseq = 1;
      private long imageLseq_ ;
      public boolean hasImageLseq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getImageLseq() {
        return imageLseq_;
      }
      public Builder setImageLseq(long value) {
        bitField0_ |= 0x00000001;
        imageLseq_ = value;
        onChanged();
        return this;
      }
      public Builder clearImageLseq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imageLseq_ = 0L;
        onChanged();
        return this;
      }
      
      // optional fixed64 imageRseq = 2;
      private long imageRseq_ ;
      public boolean hasImageRseq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getImageRseq() {
        return imageRseq_;
      }
      public Builder setImageRseq(long value) {
        bitField0_ |= 0x00000002;
        imageRseq_ = value;
        onChanged();
        return this;
      }
      public Builder clearImageRseq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        imageRseq_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .sfm.DMatches matches = 3;
      private java.util.List<cvg.sfmPipeline.main.MatchesOutMessage.DMatches> matches_ =
        java.util.Collections.emptyList();
      private void ensureMatchesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          matches_ = new java.util.ArrayList<cvg.sfmPipeline.main.MatchesOutMessage.DMatches>(matches_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          cvg.sfmPipeline.main.MatchesOutMessage.DMatches, cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder, cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder> matchesBuilder_;
      
      public java.util.List<cvg.sfmPipeline.main.MatchesOutMessage.DMatches> getMatchesList() {
        if (matchesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matches_);
        } else {
          return matchesBuilder_.getMessageList();
        }
      }
      public int getMatchesCount() {
        if (matchesBuilder_ == null) {
          return matches_.size();
        } else {
          return matchesBuilder_.getCount();
        }
      }
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatches getMatches(int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);
        } else {
          return matchesBuilder_.getMessage(index);
        }
      }
      public Builder setMatches(
          int index, cvg.sfmPipeline.main.MatchesOutMessage.DMatches value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.set(index, value);
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMatches(
          int index, cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.set(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMatches(cvg.sfmPipeline.main.MatchesOutMessage.DMatches value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMatches(
          int index, cvg.sfmPipeline.main.MatchesOutMessage.DMatches value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(index, value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMatches(
          cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMatches(
          int index, cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMatches(
          java.lang.Iterable<? extends cvg.sfmPipeline.main.MatchesOutMessage.DMatches> values) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          super.addAll(values, matches_);
          onChanged();
        } else {
          matchesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMatches() {
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      public Builder removeMatches(int index) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.remove(index);
          onChanged();
        } else {
          matchesBuilder_.remove(index);
        }
        return this;
      }
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder getMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().getBuilder(index);
      }
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder getMatchesOrBuilder(
          int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);  } else {
          return matchesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder> 
           getMatchesOrBuilderList() {
        if (matchesBuilder_ != null) {
          return matchesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matches_);
        }
      }
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder addMatchesBuilder() {
        return getMatchesFieldBuilder().addBuilder(
            cvg.sfmPipeline.main.MatchesOutMessage.DMatches.getDefaultInstance());
      }
      public cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder addMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().addBuilder(
            index, cvg.sfmPipeline.main.MatchesOutMessage.DMatches.getDefaultInstance());
      }
      public java.util.List<cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder> 
           getMatchesBuilderList() {
        return getMatchesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cvg.sfmPipeline.main.MatchesOutMessage.DMatches, cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder, cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder> 
          getMatchesFieldBuilder() {
        if (matchesBuilder_ == null) {
          matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cvg.sfmPipeline.main.MatchesOutMessage.DMatches, cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder, cvg.sfmPipeline.main.MatchesOutMessage.DMatchesOrBuilder>(
                  matches_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          matches_ = null;
        }
        return matchesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sfm.MatchesProto)
    }
    
    static {
      defaultInstance = new MatchesProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sfm.MatchesProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sfm_DMatches_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sfm_DMatches_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sfm_MatchesProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sfm_MatchesProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmatches.proto\022\003sfm\"P\n\010DMatches\022\020\n\010quer" +
      "yIdx\030\001 \001(\r\022\020\n\010trainIdx\030\002 \001(\r\022\016\n\006imgIdx\030\003" +
      " \001(\r\022\020\n\010distance\030\004 \001(\002\"T\n\014MatchesProto\022\021" +
      "\n\timageLseq\030\001 \001(\006\022\021\n\timageRseq\030\002 \001(\006\022\036\n\007" +
      "matches\030\003 \003(\0132\r.sfm.DMatchesB)\n\024cvg.sfmP" +
      "ipeline.mainB\021MatchesOutMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sfm_DMatches_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sfm_DMatches_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sfm_DMatches_descriptor,
              new java.lang.String[] { "QueryIdx", "TrainIdx", "ImgIdx", "Distance", },
              cvg.sfmPipeline.main.MatchesOutMessage.DMatches.class,
              cvg.sfmPipeline.main.MatchesOutMessage.DMatches.Builder.class);
          internal_static_sfm_MatchesProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sfm_MatchesProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sfm_MatchesProto_descriptor,
              new java.lang.String[] { "ImageLseq", "ImageRseq", "Matches", },
              cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto.class,
              cvg.sfmPipeline.main.MatchesOutMessage.MatchesProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
