/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cvg.sfmPipeline.main;

public class MatcherFLANN extends Matcher {
  private long swigCPtr;

  public MatcherFLANN(long cPtr, boolean cMemoryOwn) {
    super(sfmmatcherJNI.MatcherFLANN_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MatcherFLANN obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sfmmatcherJNI.delete_MatcherFLANN(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MatcherFLANN(Frame arg0, Frame arg1) {
    this(sfmmatcherJNI.new_MatcherFLANN(Frame.getCPtr(arg0), arg0, Frame.getCPtr(arg1), arg1), true);
  }

  public boolean matchFrames(int arg0, int arg1) {
    return sfmmatcherJNI.MatcherFLANN_matchFrames(swigCPtr, this, arg0, arg1);
  }

  public boolean buildMatchProtoMessage() {
    return sfmmatcherJNI.MatcherFLANN_buildMatchProtoMessage(swigCPtr, this);
  }

  public byte[] getMatches() {
  return sfmmatcherJNI.MatcherFLANN_getMatches(swigCPtr, this);
}

}
