/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cvg.sfmPipeline.main;

public class sfmmatcherJNI {
  public final static native long new_Matcher();
  public final static native void delete_Matcher(long jarg1);
  public final static native long new_MatcherFLANN(long jarg1, Frame jarg1_, long jarg2, Frame jarg2_);
  public final static native boolean MatcherFLANN_matchFrames(long jarg1, MatcherFLANN jarg1_, int jarg2, int jarg3);
  public final static native boolean MatcherFLANN_buildMatchProtoMessage(long jarg1, MatcherFLANN jarg1_);
  public final static native byte[] MatcherFLANN_getMatches(long jarg1, MatcherFLANN jarg1_);
  public final static native void delete_MatcherFLANN(long jarg1);
  public final static native long new_Frame__SWIG_0();
  public final static native long new_Frame__SWIG_1(long jarg1);
  public final static native void Frame_extractFeatures(long jarg1, Frame jarg1_);
  public final static native void Frame_addFrame(long jarg1, Frame jarg1_, long jarg2);
  public final static native boolean Frame_buildFrameProtoMessage(long jarg1, Frame jarg1_, boolean jarg2);
  public final static native byte[] Frame_getFrame(long jarg1, Frame jarg1_);
  public final static native void Frame_Descriptors_set(long jarg1, Frame jarg1_, long jarg2);
  public final static native long Frame_Descriptors_get(long jarg1, Frame jarg1_);
  public final static native void delete_Frame(long jarg1);
  public final static native long MatcherFLANN_SWIGUpcast(long jarg1);
}
